/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Level3(props) {
  const { nodes, materials } = useGLTF('/models/level3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Start_3.geometry}
        material={materials['platformer.138']}
        position={[0, -3.003, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_4x4x1_green001.geometry}
        material={materials['platformer.130']}
        position={[0, -2.003, -8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_green002.geometry}
        material={materials['platformer.138']}
        position={[0, -3.003, -16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_slope_6x6x4_green001.geometry}
        material={materials['platformer.152']}
        position={[0, -0.003, -22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green001.geometry}
        material={materials['platformer.137']}
        position={[0, 1.997, -28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green002.geometry}
        material={materials['platformer.137']}
        position={[0, 1.997, -34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_green003.geometry}
        material={materials['platformer.138']}
        position={[-17, -3.003, -42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_4x4x1_green002.geometry}
        material={materials['platformer.130']}
        position={[1, -0.003, -41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_green004.geometry}
        material={materials['platformer.138']}
        position={[-17, -3.003, -48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_green005.geometry}
        material={materials['platformer.138']}
        position={[-17, -3.003, -54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x2x1_green001.geometry}
        material={materials['platformer.133']}
        position={[-17, -0.003, -60]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x2x1_green002.geometry}
        material={materials['platformer.133']}
        position={[-17, -0.003, -66]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_slope_2x6x4_green001.geometry}
        material={materials['platformer.146']}
        position={[-17, -0.003, -72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_2x2x2_green001.geometry}
        material={materials['platformer.125']}
        position={[-17, 1.997, -76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_slope_2x6x4_green002.geometry}
        material={materials['platformer.146']}
        position={[-17, 2.997, -80]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_2x2x2_green002.geometry}
        material={materials['platformer.125']}
        position={[-17, 4.997, -84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green003.geometry}
        material={materials['platformer.137']}
        position={[-20, -3.003, -100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green004.geometry}
        material={materials['platformer.137']}
        position={[-14, -3.003, -100]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green005.geometry}
        material={materials['platformer.137']}
        position={[-14, -3.003, -106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green006.geometry}
        material={materials['platformer.137']}
        position={[-20, -3.003, -106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green007.geometry}
        material={materials['platformer.137']}
        position={[-20, -3.003, -111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green008.geometry}
        material={materials['platformer.137']}
        position={[-14, -3.003, -111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green009.geometry}
        material={materials['platformer.137']}
        position={[-14, -3.003, -117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_green010.geometry}
        material={materials['platformer.137']}
        position={[-20, -3.003, -117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hoop_green001.geometry}
        material={materials['platformer.112']}
        position={[-14, -1.003, -115]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hoop_green002.geometry}
        material={materials['platformer.112']}
        position={[-20, -1.003, -106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4008.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -122]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4009.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4010.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -130]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4011.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4012.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -138]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4013.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -142]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4014.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4015.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -150]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4016.geometry}
        material={materials['platformer.350']}
        position={[-21, -2.003, -146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4017.geometry}
        material={materials['platformer.350']}
        position={[-21, -2.003, -150]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4018.geometry}
        material={materials['platformer.350']}
        position={[-13, -2.003, -146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4019.geometry}
        material={materials['platformer.350']}
        position={[-13, -2.003, -150]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.End_3.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -154]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4021.geometry}
        material={materials['platformer.350']}
        position={[-17, -2.003, -158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4022.geometry}
        material={materials['platformer.350']}
        position={[-21, -2.003, -154]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4023.geometry}
        material={materials['platformer.350']}
        position={[-21, -2.003, -158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4024.geometry}
        material={materials['platformer.350']}
        position={[-13, -2.003, -154]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4025.geometry}
        material={materials['platformer.350']}
        position={[-13, -2.003, -158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.signage_finish_wide001.geometry}
        material={materials['platformer.363']}
        position={[-17, -1.503, -152]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.signage_finish_wide_board001.geometry}
          material={materials['platformer.363']}
          position={[0, 4, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/level3.glb')
