/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useFrame } from "@react-three/fiber";

export function Level3(props) {
  const { nodes, materials } = useGLTF("/models/level3.glb");
  const platform = useRef();
  const platformX = useRef();
  const directionX = useRef(1);
  const direction = useRef(1);

  const MIN_Y = -4.5;
  const MAX_Y = -2.0;
  const SPEED = 1.2;

  const MIN_X = -2;
  const MAX_X = 10;

  useFrame(() => {
    // 1. Vertical Platform Logic (Existing)
    if (platform.current) {
      const y = platform.current.translation().y;
      if (y >= MAX_Y) direction.current = -1;
      if (y <= MIN_Y) direction.current = 1;

      platform.current.setLinvel(
        { x: 0, y: SPEED * direction.current, z: 0 },
        true
      );
    }

    // 2. Horizontal Platform Logic (New)
    if (platformX.current) {
      const x = platformX.current.translation().x;

      // Check boundaries
      if (x >= MAX_X) directionX.current = -1;
      if (x <= MIN_X) directionX.current = 1;

      // Move along X axis
      platformX.current.setLinvel(
        { x: SPEED * directionX.current, y: 0, z: 0 },
        true
      );
    }
  });
  return (
    <group {...props} dispose={null}>
      <RigidBody
        ref={platform}
        type="kinematicVelocity"
        position={[0, -3.141, -8]}
        name="platform"
        colliders={"trimesh"}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_4x4x1_green001.geometry}
          material={materials["platformer.130"]}
          // position={[0, -3.141, -8]}
        />
      </RigidBody>

      <RigidBody
        ref={platformX}
        type="kinematicVelocity"
        position={[1, -0.141, -41]}
        name="platform"
        colliders={"trimesh"}
        friction={1}
        linearDamping={5}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_4x4x1_green002.geometry}
          material={materials["platformer.130"]}
          // position={[1, -0.141, -41]}
        />
      </RigidBody>

      <RigidBody type="fixed" colliders="trimesh" name="platform">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Start_3.geometry}
          material={materials["platformer.138"]}
          position={[0, -4.141, 0]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green002.geometry}
          material={materials["platformer.138"]}
          position={[0, -4.141, -16]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_slope_6x6x4_green001.geometry}
          material={materials["platformer.152"]}
          position={[0, -1.141, -22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x2_green001.geometry}
          material={materials["platformer.137"]}
          position={[0, 0.859, -28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x2_green002.geometry}
          material={materials["platformer.137"]}
          position={[0, 0.859, -34]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green003.geometry}
          material={materials["platformer.138"]}
          position={[-17, -4.141, -42]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green004.geometry}
          material={materials["platformer.138"]}
          position={[-17, -4.141, -48]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green005.geometry}
          material={materials["platformer.138"]}
          position={[-17, -4.141, -54]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x2x1_green001.geometry}
          material={materials["platformer.133"]}
          position={[-17, -1.141, -60]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x2x1_green002.geometry}
          material={materials["platformer.133"]}
          position={[-17, -1.141, -66]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_slope_2x6x4_green001.geometry}
          material={materials["platformer.146"]}
          position={[-17, -1.141, -72]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_2x2x2_green001.geometry}
          material={materials["platformer.125"]}
          position={[-17, 0.859, -76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_slope_2x6x4_green002.geometry}
          material={materials["platformer.146"]}
          position={[-17, 1.859, -80]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_2x2x2_green002.geometry}
          material={materials["platformer.125"]}
          position={[-17, 3.859, -84]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green001.geometry}
          material={materials["platformer.138"]}
          position={[-20, -4.141, -93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green006.geometry}
          material={materials["platformer.138"]}
          position={[-14, -4.141, -93]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green007.geometry}
          material={materials["platformer.138"]}
          position={[-20, -4.141, -109]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green008.geometry}
          material={materials["platformer.138"]}
          position={[-14, -4.141, -109]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green009.geometry}
          material={materials["platformer.138"]}
          position={[-20, -4.141, -133]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x4_green010.geometry}
          material={materials["platformer.138"]}
          position={[-14, -4.141, -133]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_4x4x1_green003.geometry}
          material={materials["platformer.130"]}
          position={[-14, -1.141, -115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x2002.geometry}
          material={materials["platformer.348"]}
          position={[-20, -1.141, -97]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x2003.geometry}
          material={materials["platformer.348"]}
          position={[-20, -1.141, -99]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x2004.geometry}
          material={materials["platformer.348"]}
          position={[-20, -1.141, -101]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x2005.geometry}
          material={materials["platformer.348"]}
          position={[-20, -1.141, -103]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x2006.geometry}
          material={materials["platformer.348"]}
          position={[-20, -1.141, -105]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4008.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -138]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4009.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -142]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4010.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -146]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4011.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -150]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4012.geometry}
          material={materials["platformer.350"]}
          position={[-21, -1.141, -150]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4013.geometry}
          material={materials["platformer.350"]}
          position={[-13, -1.141, -150]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4014.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4015.geometry}
          material={materials["platformer.350"]}
          position={[-21, -1.141, -154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4016.geometry}
          material={materials["platformer.350"]}
          position={[-13, -1.141, -154]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4017.geometry}
          material={materials["platformer.350"]}
          position={[-17, -1.141, -158]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4018.geometry}
          material={materials["platformer.350"]}
          position={[-21, -1.141, -158]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_4x4019.geometry}
          material={materials["platformer.350"]}
          position={[-13, -1.141, -158]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.flag_B_red001.geometry}
          material={materials["platformer.191"]}
          position={[-16.961, -0.641, -153.659]}
          rotation={[0, 1.571, 0]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/level3.glb");
