/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CuboidCollider } from "@react-three/rapier";

export function Level2(props) {
  const { nodes, materials } = useGLTF("/models/level2.glb");
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" collider={false} sensor name="end">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_1.geometry}
          material={materials["platformer.304"]}
          position={[1, 1, -71.477]}
        />
        <CuboidCollider args={[2, 2, 2]} position={[1, 1, -71.477]} />
      </RigidBody>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_red001.geometry}
        material={materials["platformer.220"]}
        position={[1, 0, -6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_red002.geometry}
        material={materials["platformer.220"]}
        position={[1, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Start_1.geometry}
        material={materials["platformer.303"]}
        position={[13, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_yellow002.geometry}
        material={materials["platformer.303"]}
        position={[7, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_yellow003.geometry}
        material={materials["platformer.303"]}
        position={[1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_red003.geometry}
        material={materials["platformer.220"]}
        position={[1, 0, -53.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_red004.geometry}
        material={materials["platformer.220"]}
        position={[1, 0, -59.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4001.geometry}
        material={materials["platformer.350"]}
        position={[1, 0, -17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4003.geometry}
        material={materials["platformer.350"]}
        position={[1, 0, -21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4004.geometry}
        material={materials["platformer.350"]}
        position={[1, 3.443, -37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4005.geometry}
        material={materials["platformer.350"]}
        position={[1, 3.443, -41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4006.geometry}
        material={materials["platformer.350"]}
        position={[1, 1, -44.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_wood_4x4007.geometry}
        material={materials["platformer.350"]}
        position={[1, 1, -48.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_red001.geometry}
        material={materials["platformer.221"]}
        position={[1, 0, -32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_slope_6x6x4_yellow001.geometry}
        material={materials["platformer.318"]}
        position={[1, 0, -26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hoop_yellow001.geometry}
        material={materials["platformer.278"]}
        position={[1, 3.943, -42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.strut_vertical003.geometry}
        material={materials["platformer.369"]}
        position={[-0.696, 1.489, -42.721]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.strut_vertical004.geometry}
        material={materials["platformer.369"]}
        position={[2.714, 1.489, -42.721]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_slope_6x6x4_yellow002.geometry}
        material={materials["platformer.318"]}
        position={[1, 1, -65.482]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x4_yellow002.geometry}
        material={materials["platformer.304"]}
        position={[1, 1, -77.484]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_yellow004.geometry}
        material={materials["platformer.303"]}
        position={[6.971, 3, -71.456]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.platform_6x6x2_yellow005.geometry}
        material={materials["platformer.303"]}
        position={[-5, 3, -71.456]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flag_C_red001.geometry}
        material={materials["platformer.192"]}
        position={[1, 5, -72]}
        rotation={[0, 1.571, 0]}
      />
    </group>
  );
}

useGLTF.preload("/level2.glb");
