/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { CuboidCollider, RigidBody } from "@react-three/rapier";
import { useFrame } from "@react-three/fiber";

const randomBetween = (min, max) => min + Math.random() * (max - min);

export function Level4(props) {
  const { nodes, materials } = useGLTF("/models/level4.glb");
  const platformY = useRef();
  const SPEED = 1.8;

  const directionY = useRef(1);

  const MIN_Y = 0;
  const MAX_Y = 6;

  const p1 = useRef();
  const p2 = useRef();
  const p3 = useRef();
  const p4 = useRef();
  const p5 = useRef();

  const dir1 = useRef(1);
  const dir2 = useRef(-1);
  const dir3 = useRef(1);
  const dir4 = useRef(-1);
  const dir5 = useRef(1);

  const speed1 = useRef(randomBetween(0.8, 1.8));
  const speed2 = useRef(randomBetween(0.8, 1.8));
  const speed3 = useRef(randomBetween(0.8, 1.8));
  const speed4 = useRef(randomBetween(0.8, 1.8));
  const speed5 = useRef(randomBetween(0.8, 1.8));

  const MIN_X = -4;
  const MAX_X = 4;

  useFrame(() => {
    const y = platformY.current.translation().y;
    if (y >= MAX_Y) directionY.current = -1;
    if (y <= MIN_Y) directionY.current = 1;
    platformY.current.setLinvel(
      { x: 0, y: SPEED * directionY.current, z: 0 },
      true
    );

    const moveX = (ref, dir, speed) => {
      if (!ref.current) return;

      const x = ref.current.translation().x;

      if (x >= MAX_X) dir.current = -1;
      if (x <= MIN_X) dir.current = 1;

      ref.current.setLinvel(
        { x: speed.current * dir.current, y: 0, z: 0 },
        true
      );
    };

    moveX(p1, dir1, speed1);
    moveX(p2, dir2, speed2);
    moveX(p3, dir3, speed3);
    moveX(p4, dir4, speed4);
    moveX(p5, dir5, speed5);
  });
  return (
    <group {...props} dispose={null}>
      <RigidBody
        ref={platformY}
        type="kinematicVelocity"
        position={[0, 0, -43]}
        name="platform"
        friction={1}
        linearDamping={5}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x1_red002.geometry}
          material={materials["platformer.219"]}
          //   position={[0, 0, -43]}
        />
      </RigidBody>

      <RigidBody
        ref={p1}
        type="kinematicVelocity"
        position={[0, 0, -72]}
        name="platform"
      >
        <mesh
          geometry={nodes.floor_wood_2x6004.geometry}
          material={materials["platformer.349"]}
          rotation={[0, 1.571, 0]}
          castShadow
          receiveShadow
        />
      </RigidBody>

      <RigidBody
        ref={p2}
        type="kinematicVelocity"
        position={[0, 0, -82]}
        name="platform"
      >
        <mesh
          geometry={nodes.floor_wood_2x6006.geometry}
          material={materials["platformer.349"]}
          rotation={[0, 1.571, 0]}
          castShadow
          receiveShadow
        />
      </RigidBody>

      <RigidBody
        ref={p3}
        type="kinematicVelocity"
        position={[0, 0, -92]}
        name="platform"
      >
        <mesh
          geometry={nodes.floor_wood_2x6007.geometry}
          material={materials["platformer.349"]}
          rotation={[0, 1.571, 0]}
          castShadow
          receiveShadow
        />
      </RigidBody>

      <RigidBody
        ref={p4}
        type="kinematicVelocity"
        position={[0, 0, -77]}
        name="platform"
      >
        <mesh
          geometry={nodes.floor_wood_2x2007.geometry}
          material={materials["platformer.348"]}
          castShadow
          receiveShadow
        />
      </RigidBody>

      <RigidBody
        ref={p5}
        type="kinematicVelocity"
        position={[0, 0, -87]}
        name="platform"
      >
        <mesh
          geometry={nodes.floor_wood_2x2008.geometry}
          material={materials["platformer.348"]}
          castShadow
          receiveShadow
        />
      </RigidBody>

      <RigidBody type="fixed" colliders="trimesh" name="platform">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x6002.geometry}
          material={materials["platformer.349"]}
          position={[0, 0, -6]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor_wood_2x6003.geometry}
          material={materials["platformer.349"]}
          position={[0, 0, -12]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x6x1_red001.geometry}
          material={materials["platformer.219"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_slope_4x6x4_red001.geometry}
          material={materials["platformer.232"]}
          position={[0, 0, -17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x2x2_red001.geometry}
          material={materials["platformer.217"]}
          position={[-1, 2, -23]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x2x2_red002.geometry}
          material={materials["platformer.217"]}
          position={[1, 2, -29]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_6x2x2_red003.geometry}
          material={materials["platformer.217"]}
          position={[-1, 2, -35]}
          rotation={[0, 1.571, 0]}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.railing_straight_double_red001.geometry}
          material={materials["platformer.240"]}
          position={[1, 4, -28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.railing_straight_double_red002.geometry}
          material={materials["platformer.240"]}
          position={[-1, 4, -33]}
        />
        <RigidBody type="fixed" collider={false} sensor name="end">
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.platform_6x6x1_red003.geometry}
            material={materials["platformer.219"]}
            position={[0, 0, -99]}
          />
          <CuboidCollider args={[2, 2, 2]} position={[0, 0, -99]} />
        </RigidBody>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x8001.geometry}
          material={materials["platformer.357"]}
          position={[0, 0, -49]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x8002.geometry}
          material={materials["platformer.357"]}
          position={[-3, 0, -52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x8003.geometry}
          material={materials["platformer.357"]}
          position={[-3, 0, -56]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x4001.geometry}
          material={materials["platformer.356"]}
          position={[1, 0, -67]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x8004.geometry}
          material={materials["platformer.357"]}
          position={[-0.526, 0, -59]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pillar_2x2x8005.geometry}
          material={materials["platformer.357"]}
          position={[1, 0, -62.195]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/level4.glb");
